apiVersion: v1
entries:
  mlflow:
  - annotations:
      category: MachineLearning
      images: |
        - name: git
          image: docker.io/bitnami/git:2.50.0-debian-12-r2
        - name: mlflow
          image: docker.io/bitnami/mlflow:3.1.1-debian-12-r1
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r47
      licenses: Apache-2.0
      tanzuCategory: application
    apiVersion: v2
    appVersion: 3.1.1
    created: "2025-07-30T12:59:34.671258288+02:00"
    dependencies:
    - condition: minio.enabled
      name: minio
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 17.x.x
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: 16.x.x
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MLflow is an open-source platform designed to manage the end-to-end
      machine learning lifecycle. It allows you to track experiments, package code
      into reproducible runs, and share and deploy models.
    digest: dd85087d679281c85e0849e32f3692e8f7bbaed3c76ee8ed57005e45f07bbbed
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mlflow/img/mlflow-stack-220x234.png
    keywords:
    - mlflow
    - models
    - python
    - machine
    - learning
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: mlflow
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mlflow
    - https://github.com/bitnami/containers/tree/main/bitnami/mlflow
    - https://github.com/mlflow/mlflow
    urls:
    - https://hardikpatel29.github.io/mlflow-chart/mlflow-5.1.0.tgz
    version: 5.1.0
generated: "2025-07-30T12:59:34.641115895+02:00"
